webtalk_init -webtalk_dir /home/cc/eecs151/sp18/class/eecs151-aaq/fpga_labs_sp18/lab7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/fifo_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 17 17:58:23 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210785086_1777526635_210661120_507" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c9b5aa6a-a118-49ae-a247-204de9ec48b6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "76cacc1533054193914fc955b78ec775" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS release 6.9 (Final)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4906 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "134324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3708950844 -regid "210785086_1777526635_210661120_507" -xml /home/cc/eecs151/sp18/class/eecs151-aaq/fpga_labs_sp18/lab7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/fifo_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cc/eecs151/sp18/class/eecs151-aaq/fpga_labs_sp18/lab7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/fifo_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cc/eecs151/sp18/class/eecs151-aaq/fpga_labs_sp18/lab7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/fifo_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
