# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache {C:/Users/David Hooper/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-9552-DESKTOP-DAEE3VS/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/fpga_labs_sp18/lab4/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/fpga_labs_sp18/lab4/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_output_repo c:/fpga_labs_sp18/lab4/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/sources_1/imports/new/util.vh
read_verilog -library xil_defaultlib {
  C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/sources_1/imports/new/button_parser.v
  C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/sources_1/imports/new/debouncer.v
  C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/sources_1/imports/new/edge_detector.v
  C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/sources_1/imports/new/synchronizer.v
  C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/sources_1/imports/new/debouncer_fpga_test.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/constrs_1/imports/constrs_1/PYNQ-Z1_C.xdc
set_property used_in_implementation false [get_files C:/fpga_labs_sp18/lab4/project_1/project_1.srcs/constrs_1/imports/constrs_1/PYNQ-Z1_C.xdc]


synth_design -top debouncer_fpga_test -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef debouncer_fpga_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file debouncer_fpga_test_utilization_synth.rpt -pb debouncer_fpga_test_utilization_synth.pb"
