# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param xicom.use_bs_reader 1
  set_param synth.incrementalSynthesisCache {C:/Users/David Hooper/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-9552-DESKTOP-DAEE3VS/incrSyn}
  create_project -in_memory -part xc7z020clg400-3
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/fpga_labs_sp18/lab4/lab4/lab4.cache/wt [current_project]
  set_property parent.project_path C:/fpga_labs_sp18/lab4/lab4/lab4.xpr [current_project]
  set_property ip_output_repo C:/fpga_labs_sp18/lab4/lab4/lab4.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet C:/fpga_labs_sp18/lab4/lab4/lab4.runs/synth_1/debouncer_fpga_test.dcp
  read_xdc C:/fpga_labs_sp18/lab4/lab4/lab4.srcs/constrs_1/imports/constrs_1/PYNQ-Z1_C.xdc
  link_design -top debouncer_fpga_test -part xc7z020clg400-3
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force debouncer_fpga_test_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file debouncer_fpga_test_drc_opted.rpt -pb debouncer_fpga_test_drc_opted.pb -rpx debouncer_fpga_test_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  implement_debug_core 
  place_design 
  write_checkpoint -force debouncer_fpga_test_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file debouncer_fpga_test_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file debouncer_fpga_test_utilization_placed.rpt -pb debouncer_fpga_test_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file debouncer_fpga_test_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force debouncer_fpga_test_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file debouncer_fpga_test_drc_routed.rpt -pb debouncer_fpga_test_drc_routed.pb -rpx debouncer_fpga_test_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file debouncer_fpga_test_methodology_drc_routed.rpt -pb debouncer_fpga_test_methodology_drc_routed.pb -rpx debouncer_fpga_test_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file debouncer_fpga_test_power_routed.rpt -pb debouncer_fpga_test_power_summary_routed.pb -rpx debouncer_fpga_test_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file debouncer_fpga_test_route_status.rpt -pb debouncer_fpga_test_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file debouncer_fpga_test_timing_summary_routed.rpt -rpx debouncer_fpga_test_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file debouncer_fpga_test_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file debouncer_fpga_test_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force debouncer_fpga_test_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  catch { write_mem_info -force debouncer_fpga_test.mmi }
  write_bitstream -force debouncer_fpga_test.bit 
  catch {write_debug_probes -quiet -force debouncer_fpga_test}
  catch {file copy -force debouncer_fpga_test.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

